AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  nested

  Sample SAM Template for nested

Metadata:
  AWS::ServerlessRepo::Application:
    Name: nested-app-test-child
    Description: An example stack to test nested app support
    Author: sam
    SpdxLicenseId: Apache-2.0
    HomePageUrl: https://github.com/user1/my-app-project
    SemanticVersion: '0.0.1'
    SourceCodeUrl: https://github.com/user1/my-app-project

Resources:
  Child:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./grand-child.yaml

  StockCheckerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      PackageType: Image
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
    Metadata:
      DockerTag: nodejs12.x-v1
      DockerContext: functions/stock-checker/
      Dockerfile: Dockerfile

Outputs:
  TransactionTableName:
    Value: !GetAtt Child.Outputs.TransactionTableName
  StockCheckerFunctionArn:
    Value: !GetAtt StockCheckerFunction.Arn
  StockSellerFunctionArn:
    Value: !GetAtt Child.Outputs.StockSellerFunctionArn
  StockCheckerFunctionName:
    Value: !Ref StockCheckerFunction
  StockSellerFunctionName:
    Value: !GetAtt Child.Outputs.StockSellerFunctionName
