AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  nested

  Sample SAM Template for nested
Metadata:
  AWS::ServerlessRepo::Application:
    Name: nested-app-test-grandchild
    Description: An example stack to test nested app support
    Author: sam
    SpdxLicenseId: Apache-2.0
    HomePageUrl: https://github.com/user1/my-app-project
    SemanticVersion: '0.0.1'
    SourceCodeUrl: https://github.com/user1/my-app-project

Resources:
  TransactionTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  StockSellerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock-seller/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Layers:
        - !Ref Node12201Runtime
  
  Node12201Runtime:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: nodejs12.x
    Properties:
      LayerName: ALayer
      ContentUri: layer
      CompatibleRuntimes: 
        - nodejs12.x

Outputs:
  TransactionTableName:
    Value: !Ref TransactionTable
  StockSellerFunctionArn:
    Value: !GetAtt StockSellerFunction.Arn
  StockSellerFunctionName:
    Value: !Ref StockSellerFunction
