version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-nested-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qtl95tb0hf9t"
s3_prefix = "test-nested-stack"
region = "us-west-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
